### variables
@url1 = http://localhost:3002
@url = https://app2.anditakaesar.com

### GET
GET {{url}}/card
Content-Type: application/json

### get
GET {{url}}/card/1
Content-Type: application/json

### CREATE
POST {{url}}/card
Content-Type: application/json

{
    "nama": "Andita Again",
    "alamat": "Jalan Raya",
    "phones": ["0121234", "1203847"]
}

### UPDATE
PATCH {{url}}/card/20
Content-Type: application/json

{
    "nama": "Andita Test",
    "alamat": "Jalan Raya",
    "phones": ["01234120", "23452345"]
}

### DELETE
DELETE  {{url}}/card/33
Content-Type: application/json

###################################