### variables
@url = http://localhost:3002

### GET
GET {{url}}/user
Content-Type: application/json

### GET
GET {{url}}/user/19
Content-Type: application/json

### CREATE
POST {{url}}/user
Content-Type: application/json

{
    "firstname": "Testing",
    "lastname": "Again",
    "email": "test@email.com",
    "active": true
}

### PATCH // UPDATE
PATCH {{url}}/user/19
Content-Type: application/json

{
    "firstname": "Andita Hehe",
    "active": false
}

### DELETE
DELETE  {{url}}/user/1
Content-Type: application/json